### ISSUE TITLE
doesn't work with cc

### ISSUE THREAD

**Issue by Glitter01** [thepancake1/TS4-SimRipper#1]
I downloaded the new version, and now all my cc sims are bodyless. They only have heads. Redownloaded from MTS for the older version and that still works with my cc

**Comment by thepancake1** [comment]
Hiya! Somebody else has reported already. I'll look into this issue in the morning.

**Comment by thepancake1** [comment]
> I downloaded the new version, and now all my cc sims are bodyless. They only have heads. Redownloaded from MTS for the older version and that still works with my cc

Hiya! Can you test this new version to see if it fixes the issue?
[TS4SimRipper_4_0_3.zip](https://github.com/thepancake1/TS4-SimRipper/files/8056565/TS4SimRipper_4_0_3.zip)

**Comment by MalikVelkari** [comment]
> > I downloaded the new version, and now all my cc sims are bodyless. They only have heads. Redownloaded from MTS for the older version and that still works with my cc
> 
> Hiya! Can you test this new version to see if it fixes the issue? [TS4SimRipper_4_0_3.zip](https://github.com/thepancake1/TS4-SimRipper/files/8056565/TS4SimRipper_4_0_3.zip)

This fixed it, but I still see some mods getting index issues

**Comment by thepancake1** [comment]
> > > I downloaded the new version, and now all my cc sims are bodyless. They only have heads. Redownloaded from MTS for the older version and that still works with my cc
> > 
> > 
> > Hiya! Can you test this new version to see if it fixes the issue? [TS4SimRipper_4_0_3.zip](https://github.com/thepancake1/TS4-SimRipper/files/8056565/TS4SimRipper_4_0_3.zip)
> 
> This fixed it, but I still see some mods getting index issues, usually talking about the min-max and negative values

How many cc packages do you have? This newer version should fix more issues.

[TS4SimRipper_4_0_3.zip](https://github.com/thepancake1/TS4-SimRipper/files/8064136/TS4SimRipper_4_0_3.zip)

**Comment by Glitter01** [comment]
> > I downloaded the new version, and now all my cc sims are bodyless. They only have heads. Redownloaded from MTS for the older version and that still works with my cc
> 
> Hiya! Can you test this new version to see if it fixes the issue? [TS4SimRipper_4_0_3.zip](https://github.com/thepancake1/TS4-SimRipper/files/8056565/TS4SimRipper_4_0_3.zip)

This works for my sims now!

**Comment by thepancake1** [comment]
That's great! I'll be closing thee issue now.
