### ISSUE TITLE
All sims are missing faces

### ISSUE THREAD

**Issue by simnights** [thepancake1/TS4-SimRipper#3]
I just updated my game files to the newest version, not sure if that's part of the issue, but none of the sims show up with faces in the ripper. Also it doesn't seem that any EA/game content is loading, only CC. As in my sims are completely invisible in an all-EA outfit, except if they have CC hair. I included one of the sim error logs but it's every sim.

[Errors.txt](https://github.com/thepancake1/TS4-SimRipper/files/8075596/Errors.txt)

![15-02-2022 19-02-28](https://user-images.githubusercontent.com/99772892/154171651-259ebc98-36af-40d1-bfa7-892b86f35fd9.png)

**Comment by morganhay** [comment]
I'm having the same issue since the new game update
![image](https://user-images.githubusercontent.com/99811362/154272139-e6ff9c88-aad4-461b-a180-945640eef57e.png)

**Comment by thepancake1** [comment]
Hiya, this is due to the new game patch updating the resource version used by EA CAS Parts. I'll fix it soon.

**Comment by thepancake1** [comment]
Hey there. Cmar provided a fix which I've added in the latest version. I'll be closing this issue now.
